---
- name: Installer K3s (cluster Kubernetes léger)
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Attendre que K3s soit prêt
  shell: /usr/local/bin/kubectl get nodes
  register: k3s_status
  retries: 10
  delay: 10
  until: k3s_status.rc == 0

- name: Créer le dossier kubeconfig pour mariem
  file:
    path: /home/mariem/.kube
    state: directory
    owner: mariem
    group: mariem
    mode: '0755'

- name: Copier le kubeconfig pour l'utilisateur mariem
  command: >
    cp /etc/rancher/k3s/k3s.yaml /home/mariem/.kube/config
  args:
    creates: /home/mariem/.kube/config

- name: Changer le propriétaire du kubeconfig
  file:
    path: /home/mariem/.kube/config
    owner: mariem
    group: mariem
    mode: '0644'
